### ISSUE TITLE
[Request] Make previous "Extra Loot" mod standalone or addon

### ISSUE THREAD

**Issue by elhertz** [Karashok-Leo/Loot-Patcher#1]
Hello! I was going to use the previous version of this mod (well, it's an entirely different mod at this point) to pair it up with [RPGDifficulty](https://modrinth.com/mod/rpgdifficulty)'s mob attribute scaling, but found out that you scraped the project and removed the modrinth page. Is there a reason behind this? is there a possibility for it to come back as a standalone mod or maybe as an addon for Loot Patcher? maybe you are planning to add the previous attribute-condition feature to the current version?

**Comment by Karashok-Leo** [comment]
Sorry for the delayed response. I thought no one would need this feature, so I deleted it directly. If you need it, I will develop another mod specifically to implement this feature. (In addition, the old project has not been deleted, only the name has been changed, which means you can still download the old version of Extra Loot from the Loot Patcher page)

**Comment by elhertz** [comment]
> If you need it, I will develop another mod specifically to implement this feature. (In addition, the old project has not been deleted, only the name has been changed, which means you can still download the old version of Extra Loot from the Loot Patcher page)

That would be awesome! I think you should also link RpgDifficulty, Nox, or other mob-related mods in your mod's page (the ones  that modify attributes that could be used along your mod), so people find it easier to use Extra Loot

**Comment by Karashok-Leo** [comment]
[Attribute Loot Condition](https://modrinth.com/mod/attribute-loot-condition) is available now in modrith. If you have any questions, you can leave a message on the issue tracker there.
